### ISSUE TITLE
Document how to use configOverrrides to configure oauth authentication

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/superset-operator#342]
Currently we support ldap as authentication backend, but sometimes it can be preferrable to integrate via oauth, which has the benefits of:
- users not having to login twice
- making use of extra security steps like 2fa the oauth provider may have set up

Superset does support integrating with oauth providers, but it seems to be a bit of manual effort: https://superset.apache.org/docs/installation/configuring-superset/#custom-oauth2-configuration

We should investigate how we can conveniently add this to the operator, or failing that, if we can at least provide a workaround to inject the necessary config to get this to work as an interim solution.

**Comment by siegfriedweber** [comment]
Changes are necessary to enable authentication via OAuth2.

# Product image

Superset requires [Authlib](https://authlib.org/) for OAuth support. This library must be added to the Superset image with `pip install authlib`.

The latest version of Superset which we currently support is 1.5.1. This version uses Flask-AppBuilder 3.4.5 which supports the following OAuth providers:
- Azure
- GitHub
- Google
- LinkedIn
- Okta
- OpenShift
- Twitter

see https://github.com/dpgaspar/Flask-AppBuilder/blob/v3.4.5/flask_appbuilder/security/manager.py#L566-L648

Superset version 2.0.1 (requested in #237) uses Flask-AppBuilder 4.1.3 which additionally supports Keycloak.

Other OAuth providers can be configured by providing a custom SecurityManager.

# Cluster configuration

The proper solution would be to implement an AuthenticationClass for OAuth.

Alternatively the configuration can also be provided in the `configOverrides` section:

```
apiVersion: superset.stackable.tech/v1alpha1
kind: SupersetCluster
metadata:
  name: superset
spec:
  image:
    productVersion: 2.0.1
    stackableVersion: 23.4.0-rc3
  credentialsSecret: superset-credentials
  authenticationConfig:
    userRegistration: true
    userRegistrationRole: Admin
  nodes:
    configOverrides:
      superset_config.py:
        AUTH_TYPE: AUTH_OAUTH
        OAUTH_PROVIDERS: |-
          [
            { 'name': 'keycloak',
              'icon': 'fa-key',
              'token_key': 'access_token',
              'remote_app': {
                  'client_id': 'superset',
                  'client_kwargs': {
                      'scope': 'email profile openid'
                  },
                  'server_metadata_url': 'http://keycloak.default.svc.cluster.local:8080/realms/superset/.well-known/openid-configuration',
              },
            }
          ]
    roleGroups:
      default:
        replicas: 1
```

(This cluster specification works only under laboratory conditions.)

# Operator

`userRegistration` and `userRegistrationRole` are only set if also an `authenticationClass` is provided. The specification above only works if this constraint is removed. `userRegistration` cannot be set in `configOverrides` because a boolean is expected and its value would be parsed as a string.

**Comment by sbernauer** [comment]
We need to properly refine this tickets (especially the scope) before we can start implementing it

**Comment by maltesander** [comment]
We need to add another `AuthenticationClassProvider` for OAuth2. Superset and the flask-appbuilder offer various providers (https://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-oauth). 

superset 1.4 -> flask-appbuilder 3.4.3
superset 1.5 -> flask-appbuilder 3.4.5
superset 2.0 -> flask-appbuilder 4.1.3
superset 2.1 -> flask-appbuilder 4.3.0

The configuration is pretty stable (some new providers are introduced from time to time). 

This basically requires three changes:
- Add https://authlib.org/
- Add AuthenticationClass to operator-rs
- Adapt superset 

## Questions:

- Do we want to start with just superset or go for another AuthenticationClass in operator-rs?
- Do we "invent" a stackable naming or stick to the flask app builder (superset/airflow) values?
- Do we want a struct for each OAuth provider or summarize as far as possible with Options?
- Which OAuth2 providers do we want to support from the beginning?

## CRD proposal

```
#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OauthAuthenticationProvider {
    // provider:
    //   oauth:
    //     providers:
    //     - google:
    //         clientId: ...
    //         clientSecret: ...
    //     - twitter: ...
    pub providers: Vec<OauthProvider>,
}

#[derive(Clone, Debug, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum OauthProvider {
    //Azure,
    //Google,
    //LinkedIn,

    // Do we want a struct for each provider or summarize as far as possible?
    Twitter(OauthTwitter),
}

#[derive(Clone, Debug, Default, Deserialize, Eq, JsonSchema, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct OauthTwitter {
    pub api_base_url: String,
    pub request_token_url: Option<String>,
    pub access_token_url: Option<String>,
    pub auth_url: Option<String>,
    pub redirect_url: Option<String>,
    pub port: Option<u16>,
    // Should come from secret?
    pub client_id: String,
    // Should come from secret?
    pub client_secret: Option<String>,
    pub scopes: Vec<String>,
    pub tls: Option<Tls>,
}
```

## TODO:

- [ ] Add https://authlib.org/ to superset docker image (via pip)
- [ ] Introduce new AuthenticationClassProvider for OAuth 2.0 (in operator-rs). This should itself be another enum (or better vec of enum) to represent different OAuth2 providers (google, twitter etc.). This is possibly worth of an ADR or at least an architecture discussion, depending on which products we want to support OAuth2 in the future. 
- [ ] Research possible OAuth2 servers for integration testing (e.g. like https://doc.networknt.com/getting-started/light-oauth2/) in terms of licensing and best fit for us
- [ ] Implement superset OAuth2 based on the new AuthenticationClassProvider
- [ ] Implement integration tests
- [ ] Document OAuth2 and provide example(s)

**Comment by soenkeliebau** [comment]
We agreed to proceed with config overrides (and potentially pod overrides in case they are needed) for now.
